//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp7.database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Historuy
    {
        public int IdProduct { get; set; }
        public string ProductName { get; set; }
        public string Count { get; set; }
        public string Date { get; set; }
    
        public virtual Product Product { get; set; }
    }
}
