//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp7.database
{
    using System;
    using System.Collections.Generic;

    public partial class Product
    {
        
        public int IdProduct { get; set; }
        public string ProductName { get; set; }
        public byte[] Image { get; set; }
        public int IdManufacturer { get; set; }
        public string Status { get; set; }
        public decimal Price { get; set; }
    
        public virtual Historuy Historuy { get; set; }
        public virtual Manufacturer Manufacturer { get; set; }
    }
}
